# Generated by Django 4.1.2 on 2023-12-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_text', models.TextField(verbose_name='Текст уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='Notify_journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_text', models.TextField(verbose_name='Текст уведомления')),
                ('sent_datetime', models.DateTimeField(verbose_name='Дата отправки уведомления')),
            ],
            options={
                'verbose_name': 'Журнал уведомления',
                'verbose_name_plural': 'Журнал уведомления',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message_text', models.TextField(verbose_name='Текст сообщения для команды /start')),
                ('help_message_text', models.TextField(verbose_name='Текст сообщения для команды /help')),
                ('notify_interval', models.IntegerField(verbose_name='Интервал отправки уведомлений (в днях)')),
                ('notify_time', models.IntegerField(verbose_name='Интервал отправки уведомлений (в днях)')),
                ('user_event_delta', models.IntegerField(verbose_name='Количество дней до события для уведомления (в днях)')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя в Телеграм')),
                ('tg_id', models.IntegerField(verbose_name='ID пользователя в Телеграм')),
                ('join_datetime', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания wish-листа')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_whishlist', to='main.user', verbose_name='Автор wish-листа')),
            ],
            options={
                'verbose_name': 'Whish-лист',
                'verbose_name_plural': 'Whish-листы',
            },
        ),
        migrations.CreateModel(
            name='Whishlist_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whish_list_title', models.CharField(max_length=255, verbose_name='Заголовок элемента Whish-листа')),
                ('Whish_list_item', models.CharField(max_length=255, verbose_name='Элемент Whish-листа')),
                ('Whish_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Whishlist_item', to='main.whishlist', verbose_name='ID Whish-листа')),
            ],
            options={
                'verbose_name': 'Элемент Whish-листа',
                'verbose_name_plural': 'Элементы Whish-листа',
            },
        ),
        migrations.CreateModel(
            name='UserEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Название события')),
                ('event_date', models.DateTimeField(verbose_name='Дата события')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Whishlist_item', to='main.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие пользователя',
                'verbose_name_plural': 'События пользователей',
            },
        ),
        migrations.CreateModel(
            name='RelatedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to='main.user', verbose_name='Первый пользователь')),
                ('second_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='main.user', verbose_name='Второй пользователь')),
            ],
            options={
                'verbose_name': 'Связанный пользователь',
                'verbose_name_plural': 'Связанные пользователи',
            },
        ),
    ]
