# Generated by Django 4.1.2 on 2023-12-16 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message_text', models.TextField(verbose_name='Текст сообщения для команды /start')),
                ('start_message_image', models.ImageField(blank=True, upload_to='photo', verbose_name='Изображение к команде /start')),
                ('create_list_text', models.TextField(verbose_name='Текст для создания ВИШ-листа')),
                ('create_list_image', models.ImageField(blank=True, upload_to='photo', verbose_name='Изображение для создания ВИШ-листа')),
                ('after_create_list_text', models.TextField(verbose_name='Текст после создания ВИШ-листа')),
                ('error_create_list_text', models.TextField(verbose_name='Текст на случай неправильного формата ввода ВИШ-листа')),
                ('find_user_text', models.TextField(verbose_name='Текст для поиска пользователя')),
                ('error_find_user_text', models.TextField(verbose_name='Текст на случай, если пользователь не найден')),
                ('whats_next_text', models.TextField(verbose_name="Текст для раздела 'Отправил, что дальше?'")),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Имя пользователя в Телеграм')),
                ('tg_id', models.IntegerField(verbose_name='ID пользователя в Телеграм')),
                ('join_datetime', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Whishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='Дата создания wish-листа')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_whishlist', to='main.users', verbose_name='Автор wish-листа')),
            ],
            options={
                'verbose_name': 'Whish-лист',
                'verbose_name_plural': 'Whish-листы',
            },
        ),
        migrations.CreateModel(
            name='Whishlist_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whish_list_title', models.CharField(max_length=255, verbose_name='Заголовок элемента Whish-листа')),
                ('Whish_list_item', models.CharField(max_length=255, verbose_name='Элемент Whish-листа')),
                ('Whish_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Whishlist_item', to='main.whishlist', verbose_name='ID Whish-листа')),
            ],
            options={
                'verbose_name': 'Элемент Whish-листа',
                'verbose_name_plural': 'Элементы Whish-листа',
            },
        ),
    ]
